controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


admin_controller:
    resource: App\Controller\AdminController
    type: annotation

client_controller:
    resource: App\Controller\ClientController
    type: annotation